---
title: "spatial_water_column_metabolism"
author: "MKAUFMAN"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## setup
```{r include=FALSE}
library(ggplot2)
#library("anytime")
#library(tidyverse)
# set working directory
#setwd("C:/Users/kauf093/OneDrive - PNNL/Documents/2020 RC2/august_manual_chamber_testing");
```

## import rate and temp data, reshape, and clean up
```{r message=FALSE}
indata<-read.csv("RC2_Minidot_lm_summary_v1.csv")
names<-rbind(as.data.frame(indata$Site_ID) ,as.data.frame(indata$Site_ID), as.data.frame(indata$Site_ID))
doslope1<-as.data.frame(indata$Dissolved_Oxygen_1_Slope)
colnames(doslope1)<-"doslope"
doslope2<-as.data.frame(indata$Dissolved_Oxygen_2_Slope)
colnames(doslope2)<-"doslope"
doslope3<-as.data.frame(indata$Dissolved_Oxygen_3_Slope)
colnames(doslope3)<-"doslope"
doslope<-rbind(doslope1,doslope2,doslope3)
doslope<-doslope*60*24

doNRMSE1<-as.data.frame(indata$Dissolved_Oxygen_1_NRMSE)
colnames(doNRMSE1)<-"doNRMSE"
doNRMSE2<-as.data.frame(indata$Dissolved_Oxygen_2_NRMSE)
colnames(doNRMSE2)<-"doNRMSE"
doNRMSE3<-as.data.frame(indata$Dissolved_Oxygen_3_NRMSE)
colnames(doNRMSE3)<-"doNRMSE"
doNRMSE<-rbind(doNRMSE1,doNRMSE2,doNRMSE3)

Tmean1<-as.data.frame(indata$Temperature_1_Mean)
colnames(Tmean1)<-"Tmean"
Tmean2<-as.data.frame(indata$Temperature_2_Mean)
colnames(Tmean2)<-"Tmean"
Tmean3<-as.data.frame(indata$Temperature_3_Mean)
colnames(Tmean3)<-"Tmean"
Tmean<-rbind(Tmean1,Tmean2,Tmean3)

rawdata<-cbind(names,doslope,doNRMSE,Tmean)
colnames(rawdata)<-c("SID","DO.slope.mgday","DO.NRMSE","T_mean")

#remove all the intermediate tables
rm(list=setdiff(ls(), "rawdata"))

#remove any rows where DO NRMSE is greater than 0.01
rawdata<-subset(rawdata, DO.NRMSE<=0.01)

#average rate and temperature data by site
site_mean <- aggregate(cbind(DO.slope.mgday,T_mean) ~ SID, data = rawdata, FUN = mean, na.rm = TRUE)

```
## import chemistry data, format, and clean up

```{r message=FALSE}
#chemistry data 
#//pnl/projects/SBR_SFA/RC1/RC2-Data-Deliveries/RC2-Spatial-Study-2021-Sample-Data/SPS_DIC_NPOC_TN_TSS.csv
chemdataheaders<-read.csv("SPS_DIC_NPOC_TN_TSS.csv",skip = 2, header = F, nrows = 1, as.is = T)
chemdata<-read.csv("SPS_DIC_NPOC_TN_TSS.csv",skip=14,header = F)
colnames(chemdata)= chemdataheaders

#site ID to vial ID mapping info
#//pnl/projects/SBR_SFA/RC2/04_Spatial_Study_2021/06_Metadata/RC2 Spatial Study (Responses) - Form Responses 1(updated 2022-05-17).csv
IDmapping<-read.csv("RC2 Spatial Study (Responses) - Form Responses 1(updated 2022-05-17).csv",header = T)
IDmapping<-data.frame(IDmapping$Site_Vial_ID_.SPS_4_digit_numeric_code,IDmapping$ID)

chemdata<-chemdata[!(chemdata$Field_Name=="#End_Data"),]
chemdata$sample_id<-substr(chemdata$Sample_Name,0,8)
chemdata$repnum<-substr(chemdata$Sample_Name,10,10)

#remove any -9999 values
chemdata$`00691_DIC_mg_per_L_as_C`[chemdata$`00691_DIC_mg_per_L_as_C` == -9999] <- NA
chemdata$`00681_NPOC_mg_per_L_as_C`[chemdata$`00681_NPOC_mg_per_L_as_C` == -9999] <- NA
chemdata$`00602_TN_mg_per_L_as_N`[chemdata$`00602_TN_mg_per_L_as_N` == -9999] <- NA
chemdata$`00530_TSS_mg_per_L`[chemdata$`00530_TSS_mg_per_L` == -9999] <- NA

#remove any values that contain data flags
chemdata$`00691_DIC_mg_per_L_as_C`<- lapply(chemdata$`00691_DIC_mg_per_L_as_C`, function(x) as.numeric(as.character(x)))
chemdata$`00681_NPOC_mg_per_L_as_C`<- lapply(chemdata$`00681_NPOC_mg_per_L_as_C`, function(x) as.numeric(as.character(x)))
chemdata$`00602_TN_mg_per_L_as_N`<- lapply(chemdata$`00602_TN_mg_per_L_as_N`, function(x) as.numeric(as.character(x)))
chemdata$`00530_TSS_mg_per_L`<- lapply(chemdata$`00530_TSS_mg_per_L`, function(x) as.numeric(as.character(x)))

#aggregate replicate values by averaging reps across sample ID
DIC<- chemdata[c("sample_id","00691_DIC_mg_per_L_as_C")]
NPOC<- chemdata[c("sample_id","00681_NPOC_mg_per_L_as_C")]
TN<- chemdata[c("sample_id","00602_TN_mg_per_L_as_N")]
TSS<- chemdata[c("sample_id","00530_TSS_mg_per_L")]

DIC$`00691_DIC_mg_per_L_as_C`<-as.numeric(unlist(DIC$`00691_DIC_mg_per_L_as_C`))
NPOC$`00681_NPOC_mg_per_L_as_C`<-as.numeric(unlist(NPOC$`00681_NPOC_mg_per_L_as_C`))
TN$`00602_TN_mg_per_L_as_N`<-as.numeric(unlist(TN$`00602_TN_mg_per_L_as_N`))
TSS$`00530_TSS_mg_per_L`<-as.numeric(unlist(TSS$`00530_TSS_mg_per_L`))

DIC <- DIC[complete.cases(DIC), ]
NPOC <- NPOC[complete.cases(NPOC), ]
TN <- TN[complete.cases(TN), ]
TSS <- TSS[complete.cases(TSS), ]

DICagg = aggregate(DIC,
                by = list(DIC$sample_id),
                FUN = mean)
NPOCagg = aggregate(NPOC,
                by = list(NPOC$sample_id),
                FUN = mean)
TNagg = aggregate(TN,
                by = list(TN$sample_id),
                FUN = mean)
TSSagg = aggregate(TSS,
                by = list(TSS$sample_id),
                FUN = mean)

chemdata_agg<-data.frame(chemdata$sample_id)
chemdata_agg<-chemdata_agg[!duplicated(chemdata_agg), ]
chemdata_agg<-sort(chemdata_agg, decreasing = FALSE)
chemdata_agg<-data.frame(chemdata_agg)
colnames(chemdata_agg)<-"sample_id"

chemdata_agg<-merge(x=chemdata_agg, y=IDmapping,by.x="sample_id",by.y="IDmapping.Site_Vial_ID_.SPS_4_digit_numeric_code", all.x=TRUE, sort = TRUE)
chemdata_agg<-chemdata_agg[!is.na(chemdata_agg$IDmapping.ID),]

chemdata_agg<-merge(x=chemdata_agg, y=DICagg,by.x="sample_id",by.y="Group.1", all.x=TRUE, sort = TRUE)
chemdata_agg <- subset(chemdata_agg, select = -(sample_id.y))

chemdata_agg<-merge(x=chemdata_agg, y=NPOCagg,by.x="sample_id",by.y="Group.1", all.x=TRUE, sort = TRUE)
chemdata_agg <- subset(chemdata_agg, select = -(sample_id.y))

chemdata_agg<-merge(x=chemdata_agg, y=TNagg,by.x="sample_id",by.y="Group.1", all.x=TRUE, sort = TRUE)
chemdata_agg <- subset(chemdata_agg, select = -(sample_id.y))

chemdata_agg<-merge(x=chemdata_agg, y=TSSagg,by.x="sample_id",by.y="Group.1", all.x=TRUE, sort = TRUE)
chemdata_agg <- subset(chemdata_agg, select = -(sample_id.y))
```

#merge rate, temp, and chem data
```{r message=FALSE}

#merge chem data with DO rate data
chemdata_merged<-merge(x=chemdata_agg, y=site_mean, by.x="IDmapping.ID", by.y="SID",all=TRUE)
#write chemdata_merged
write.csv(chemdata_merged,"chem_data.csv", row.names = FALSE)
```

#dot plot figure (comparison of repilcates)
```{r message=FALSE}
ggplot(rawdata, aes(x=SID, y=DO.slope.mgday)) + 
  stat_summary(fun=mean, geom="point", shape=18,size=3, color="red") +
  geom_dotplot(binaxis='y', stackdir='center',binwidth = 0.002,) +
  ylab("Respiration rate (mg O2/L*day)") + xlab("Site ID") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),legend.position = c(0, 0))
```

#rate histogram
```{r message=FALSE}
hist(rawdata$DO.slope.mgday,breaks=25,main="",xlab="Respiration rate (mg O2/L*day)", ylab="frequency")
```
#stream order
```{r message=FALSE}
#import stream order and catchment area data
#\\pnl\projects\SBR_SFA\RC2\07_Geospatial_Data\RC2_all_stream_Attributes_updated.csv
#\\pnl\projects\SBR_SFA\RC2\07_Geospatial_Data\RC2_all_topographic_Attributes_updated.csv

stream_order<-read.csv("RC2_all_stream_Attributes_updated.csv")
stream_order <- stream_order[,c("site_ID","StreamOrde")]

Tbasin_area<-read.csv("RC2_all_topographic_Attributes_updated.csv")
Tbasin_area <- Tbasin_area[,c("site_ID","TOT_BASIN_AREA")]

spatialdata_merged<-merge(x=chemdata_merged, y=stream_order, by.x="IDmapping.ID", by.y="site_ID")
spatialdata_merged<-merge(x=spatialdata_merged, y=Tbasin_area, by.x="IDmapping.ID", by.y="site_ID")

write.csv(spatialdata_merged,"spatial_data.csv", row.names = FALSE)

boxplot(DO.slope.mgday~StreamOrde,data=spatialdata_merged, main="",
   xlab="Stream Order", ylab="Respiration rate (mg O2/L*day)")
slope.streamorder <- lm(DO.slope.mgday ~ StreamOrde, data=spatialdata_merged)
X = sort(unique(spatialdata_merged$StreamOrde))
lines(x=1:length(X),
y=predict(slope.streamorder,data.frame(StreamOrde=X)),col="blue",lwd=2)

boxplot_linreg <- lm(DO.slope.mgday ~ StreamOrde, data=spatialdata_merged)
summary(boxplot_linreg)
```
#mean temperature
```{r message=FALSE}
plot(rawdata$T_mean, rawdata$DO.slope.mgday, pch = 16, cex = 1.3, col = "black", main = "", xlab="Mean Temperature (C)",ylab="DO slope (mg*l^-1*day^-1)")+abline(lm(`DO.slope.mgday` ~ T_mean, data=rawdata))
temp_linreg <- lm(`DO.slope.mgday` ~ T_mean, data=rawdata)
summary(temp_linreg)

```
